language: csharp

mono: none

dotnet: 2.1

script:
  - dotnet build ./ArkEcosystem.Crypto
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./ArkEcosystem.Crypto.Tests

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1
