name: Test

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened]

jobs:
    unit:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build
              run: dotnet build ./ArkEcosystem.Crypto
            - name: Unit Tests
              run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./ArkEcosystem.Crypto.Tests
